package io.github.xn32.json5k.generation

internal actual fun Double.toScientificString(): String {
    return this.asDynamic().toExponential() as String
}

internal actual fun Double.toPlainString(): String {
    check(this == 0.0 || (this > 1e-6 || this < 1e9))

    // If the invariant above is met, the default toString() method
    // provided by JavaScript prints the number in its plain format:
    val raw = toString()

    // However, we need to add an explicit decimal part if its value is
    // zero and, therefore, it was not generated by the call above:
    return if (!raw.contains('.')) {
        "$raw.0"
    } else {
        raw
    }
}
